### ISSUE TITLE
broken SHA for armadillo?

### ISSUE THREAD

**Issue by jakeChal** [PacktPublishing/Hands-On-Machine-Learning-with-CPP#4]
Was there some history rewriting on armadillo repo? Seems that `git checkout 442d52ba052115b32035a6e7dc6587bb6a462dec` gives following error:
`fatal: reference is not a tree: 442d52ba052115b32035a6e7dc6587bb6a462dec`

Can you check with `git log` if there's a branch "close" to that commit (e.g. 8.600.x)?

**Comment by Kolkir** [comment]
Hi, @jakeChal  you are right the issue exists. Looks like that the Armadillo project tree was cleaned. The oldest branch is `8.600.x` and its root commit is `eef15f8f6fc0029f598d9626ed67355ca3bbb3a0`. You can try to checkout this branch and build examples. 
Unfortunately I don't have enough resources to check if examples work with this branch  by myself. Due to the war in Ukraine I don't have access to my development environment.

**Comment by jakeChal** [comment]
Thanks @Kolkir , will try it out. Very informative resources you've assembled :+1: 
Hope you and your relatives are staying safe..
